[tool.poetry]
name = "mazegen"
version = "0.0.1"
packages = [{ include = "mazegen" }]

[tool.poetry.dependencies]
python = ">=3.10"
pydantic = "2.12.5"
numpy = "2.2.6"

[tool.poetry.group.a-maze-ing.dependencies]
mlx = { path = "libs/mlx-2.2-py3-none-any.whl" }
mypy = "1.19.1"
flake8 = "7.3.0"

[[tool.mypy.overrides]]
module = "mlx.*"
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
